import { state } from '../state.js';
import { escapeHtml } from '../utils/dom.js';
import { todayStr } from '../utils/date.js';
import { cacheEntries } from '../db/indexeddb.js';
import { enqueue } from '../db/sync.js';
import { deleteEntry } from '../entries.js';

let visibleMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1); let selectedDate=new Date();
const MONTHS=['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'];
const WEEKDAYS=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];
function dayKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function fmtDate(d){return d.toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'});}
function events(){return state.entries.filter(e=>e.type==='event').sort((a,b)=>new Date(a.event_date)-new Date(b.event_date));}
function eventCountMap(){const m=new Map(); for(const e of events()){const k=dayKey(new Date(e.event_date));m.set(k,(m.get(k)||0)+1)} return m;}
function renderMonth(){const first=new Date(visibleMonth.getFullYear(),visibleMonth.getMonth(),1);const offset=(first.getDay()+6)%7;const dim=new Date(visibleMonth.getFullYear(),visibleMonth.getMonth()+1,0).getDate();const prev=new Date(visibleMonth.getFullYear(),visibleMonth.getMonth(),0).getDate();const counts=eventCountMap();const cells=[];for(let i=0;i<42;i++){let n=i-offset+1,d,muted=false;if(n<=0){d=new Date(visibleMonth.getFullYear(),visibleMonth.getMonth()-1,prev+n);muted=true}else if(n>dim){d=new Date(visibleMonth.getFullYear(),visibleMonth.getMonth()+1,n-dim);muted=true}else d=new Date(visibleMonth.getFullYear(),visibleMonth.getMonth(),n);const k=dayKey(d),sel=k===dayKey(selectedDate),today=k===todayStr();cells.push(`<button class="calendar-cell ${muted?'muted':''} ${sel?'selected':''} ${today?'today':''}" onclick="selectCalendarDate('${k}')"><span>${d.getDate()}</span>${counts.has(k)?`<i style="background:${sel?'#fff':'var(--gesso-accent)'}"></i>`:''}</button>`)}return WEEKDAYS.map(w=>`<div class="calendar-cell weekday">${w}</div>`).join('')+cells.join('');}
function selectedEvents(){return events().filter(e=>dayKey(new Date(e.event_date))===dayKey(selectedDate));}
function upcoming(){const now=new Date();return events().filter(e=>new Date(e.event_date)>=new Date(now.getFullYear(),now.getMonth(),now.getDate())).slice(0,5);}
export function renderCalendar(){const list=document.getElementById('calendarList');if(!list)return;const se=selectedEvents();const up=upcoming();list.innerHTML=`<div class="screen-stack"><div class="page-heading-row"><div><div class="meta-small">План</div><h1 class="page-title">Календарь</h1><p class="page-description">Планируй события и важные даты</p></div><button class="primary-icon-button" onclick="openEventAdd()">＋</button></div><div class="quick-days"><button onclick="goToday()">Сегодня</button><button onclick="setRelativeDay(1)">Завтра</button><button onclick="setRelativeDay(7)">Через неделю</button></div><section class="calendar-shell"><div class="calendar-top"><button class="icon-plain" onclick="changeCalendarMonth(-1)">‹</button><div class="calendar-caption">${MONTHS[visibleMonth.getMonth()]} ${visibleMonth.getFullYear()}</div><button class="icon-plain" onclick="changeCalendarMonth(1)">›</button></div><div class="calendar-grid">${renderMonth()}</div></section><section><div class="section-head"><h2>${fmtDate(selectedDate)}</h2><button class="view-all" onclick="openEventAdd()">＋ Добавить</button></div><div class="event-card">${se.length?se.map(e=>`<div class="event-item"><span class="event-dot"></span><div class="event-main"><strong>${escapeHtml(e.title)}</strong><span>${fmtDate(new Date(e.event_date))}</span></div><div class="event-actions"><button class="icon-plain" onclick="addEventToPhoneCalendar('${e.id}')">⇩</button><button class="icon-plain" onclick="deleteEntry('${e.id}');renderCalendar()">✕</button></div></div>`).join(''):`<div class="event-empty"><div class="empty-icon">◷</div><strong>Пока нет событий</strong><span>Нажми «＋ Добавить», чтобы создать первое.</span></div>`}</div></section><section><div class="section-head"><h2>Ближайшие</h2><span class="meta-small">${up.length}</span></div><div class="upcoming-list">${up.length?up.map(e=>`<button class="upcoming-item" onclick="selectCalendarDate('${dayKey(new Date(e.event_date))}')"><span class="upcoming-date">${new Date(e.event_date).getDate()}</span><span class="upcoming-main"><strong>${escapeHtml(e.title)}</strong><small>${fmtDate(new Date(e.event_date))}</small></span><span>›</span></button>`).join(''):`<div class="dashboard-empty">Пока нет ближайших событий.</div>`}</div></section></div>`;}
export function goToday(){ const d=new Date(); selectedDate=d; visibleMonth=new Date(d.getFullYear(),d.getMonth(),1); renderCalendar(); }
export function selectCalendarDate(key){selectedDate=new Date(key+'T12:00:00');visibleMonth=new Date(selectedDate.getFullYear(),selectedDate.getMonth(),1);renderCalendar();}
export function changeCalendarMonth(dir){visibleMonth=new Date(visibleMonth.getFullYear(),visibleMonth.getMonth()+dir,1);renderCalendar();}
export function setRelativeDay(days){const d=new Date();d.setDate(d.getDate()+days);selectCalendarDate(dayKey(d));}
export function openEventAdd(){const modal=document.createElement('div');modal.className='modal-bg';modal.onclick=e=>{if(e.target===modal)modal.remove()};modal.innerHTML=`<div class="modal"><div class="modal-handle"></div><h2>Новое событие</h2><label>Название<input id="newEventTitle" placeholder="Например, встреча или дедлайн"></label><label>Дата<input id="newEventDate" type="date" value="${dayKey(selectedDate)}"></label><label>Заметка<textarea id="newEventNote" rows="3" placeholder="Необязательно"></textarea></label><button class="primary" onclick="saveNewEvent()">Добавить</button><button class="ghost" onclick="this.closest('.modal-bg').remove()">Отмена</button></div>`;document.body.appendChild(modal);}
export async function saveNewEvent(){const title=document.getElementById('newEventTitle')?.value.trim();const dateVal=document.getElementById('newEventDate')?.value;if(!title||!dateVal)return;const now=new Date().toISOString();const row={id:crypto.randomUUID(),type:'event',title,event_date:new Date(dateVal+'T12:00:00').toISOString(),user_id:state.session.user.id,created_at:now,updated_at:now,done:false,category:'Календарь'};state.entries.push(row);selectedDate=new Date(dateVal+'T12:00:00');document.querySelector('.modal-bg')?.remove();cacheEntries([row]);enqueue('entries','insert',row);renderCalendar();}
export function addEventToPhoneCalendar(id){const e=state.entries.find(x=>x.id===id);if(!e?.event_date)return;const d=new Date(e.event_date);const y=d.getUTCFullYear();const m=String(d.getUTCMonth()+1).padStart(2,'0');const day=String(d.getUTCDate()).padStart(2,'0');const ics=['BEGIN:VCALENDAR','VERSION:2.0','BEGIN:VEVENT',`UID:${e.id}@put-app`,`DTSTAMP:${d.toISOString().replace(/[-:]/g,'').split('.')[0]}Z`,`DTSTART;VALUE=DATE:${y}${m}${day}`,`SUMMARY:${e.title.replace(/\n/g,' ')}`,'END:VEVENT','END:VCALENDAR'].join('\r\n');const blob=new Blob([ics],{type:'text/calendar;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${e.title.slice(0,30)||'event'}.ics`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);}
