import { state } from '../state.js';
import { escapeHtml } from '../utils/dom.js';
import { todayStr } from '../utils/date.js';
import { cacheEntries } from '../db/indexeddb.js';
import { enqueue } from '../db/sync.js';
import { deleteEntry } from '../entries.js';
import { getCalendarOrder } from '../personalization.js';

let visibleMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1); let selectedDate=new Date();
const MONTHS=['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'];
const WEEKDAYS=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];
const icon={left:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14.5 5 8 12l6.5 7"/></svg>',right:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m9.5 5 6.5 7-6.5 7"/></svg>',edit:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 20h4L19 9l-4-4L4 16v4Z"/><path d="m13.5 6.5 4 4"/></svg>',calendar:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="4" width="18" height="17" rx="3"/><path d="M8 2v4M16 2v4M3 9h18"/></svg>',trash:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 7h14M10 11v6M14 11v6M8 7l1-3h6l1 3M7 7l1 14h8l1-14"/></svg>',plus:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v14M5 12h14"/></svg>'};
function dayKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function fmtDate(d){return d.toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'});}
function events(){return state.entries.filter(e=>e.type==='event').sort((a,b)=>new Date(a.event_date)-new Date(b.event_date));}
function eventCountMap(){const m=new Map();for(const e of events()){const k=dayKey(new Date(e.event_date));m.set(k,(m.get(k)||0)+1);}return m;}
function renderMonth(){const first=new Date(visibleMonth.getFullYear(),visibleMonth.getMonth(),1);const offset=(first.getDay()+6)%7;const dim=new Date(visibleMonth.getFullYear(),visibleMonth.getMonth()+1,0).getDate();const prev=new Date(visibleMonth.getFullYear(),visibleMonth.getMonth(),0).getDate();const counts=eventCountMap();const cells=[];for(let i=0;i<42;i++){let n=i-offset+1,d,muted=false;if(n<=0){d=new Date(visibleMonth.getFullYear(),visibleMonth.getMonth()-1,prev+n);muted=true}else if(n>dim){d=new Date(visibleMonth.getFullYear(),visibleMonth.getMonth()+1,n-dim);muted=true}else d=new Date(visibleMonth.getFullYear(),visibleMonth.getMonth(),n);const k=dayKey(d),sel=k===dayKey(selectedDate),today=k===todayStr();cells.push(`<button class="calendar-cell ${muted?'muted':''} ${sel?'selected':''} ${today?'today':''}" onclick="selectCalendarDate('${k}')"><span>${d.getDate()}</span>${counts.has(k)?`<i style="background:${sel?'#fff':'var(--gesso-accent)'}"></i>`:''}</button>`);}return WEEKDAYS.map(w=>`<div class="calendar-cell weekday">${w}</div>`).join('')+cells.join('');}
function selectedEvents(){return events().filter(e=>dayKey(new Date(e.event_date))===dayKey(selectedDate));}
function upcoming(){const now=new Date();return events().filter(e=>new Date(e.event_date)>=new Date(now.getFullYear(),now.getMonth(),now.getDate())).slice(0,5);}
function calendarSection(){return `<section class="calendar-shell"><div class="calendar-top"><button class="calendar-icon-btn" onclick="changeCalendarMonth(-1)" aria-label="Предыдущий месяц">${icon.left}</button><div class="calendar-caption">${MONTHS[visibleMonth.getMonth()]} ${visibleMonth.getFullYear()}</div><div style="display:flex;gap:2px"><button class="calendar-icon-btn" onclick="goToday()" aria-label="Сегодня">${icon.calendar}</button><button class="calendar-icon-btn" onclick="changeCalendarMonth(1)" aria-label="Следующий месяц">${icon.right}</button></div></div><div class="calendar-grid">${renderMonth()}</div></section>`;}
function selectedSection(se){return `<section><div class="section-head"><div><div class="meta-small">Выбранная дата</div><h2>${fmtDate(selectedDate)}</h2></div><button class="view-all" onclick="openEventAdd()">Добавить</button></div><div class="event-card">${se.length?se.map(e=>`<div class="event-item"><span class="event-dot"></span><div class="event-main"><strong>${escapeHtml(e.title)}</strong><span>${fmtDate(new Date(e.event_date))}</span></div><div class="event-actions"><button class="calendar-icon-btn small" onclick="editEvent('${e.id}')" aria-label="Редактировать">${icon.edit}</button><button class="calendar-icon-btn small danger" onclick="deleteCalendarEvent('${e.id}')" aria-label="Удалить">${icon.trash}</button></div></div>`).join(''):`<div class="event-empty"><div class="empty-icon">◷</div><strong>Пока нет событий</strong><span>Добавь событие для этой даты.</span><button class="primary-pill" style="margin-top:6px" onclick="openEventAdd()">＋ Событие</button></div>`}</div></section>`;}
function upcomingSection(up){return `<section><div class="section-head"><h2>Ближайшие события</h2><span class="meta-small">${up.length}</span></div><div class="upcoming-list">${up.length?up.map(e=>`<button class="upcoming-item" onclick="selectCalendarDate('${dayKey(new Date(e.event_date))}')"><span class="upcoming-date">${new Date(e.event_date).getDate()}</span><span class="upcoming-main"><strong>${escapeHtml(e.title)}</strong><small>${fmtDate(new Date(e.event_date))}</small></span>${icon.right}</button>`).join(''):`<div class="dashboard-empty">Пока нет ближайших событий.</div>`}</div></section>`;}

export function renderCalendar(){
  const list=document.getElementById('calendarList'); if(!list)return; const se=selectedEvents(), up=upcoming();
  const sections={calendar:calendarSection(),selected:selectedSection(se),upcoming:upcomingSection(up)};
  const order=getCalendarOrder();
  list.innerHTML=`<div class="screen-stack"><div class="page-heading-row"><div><div class="meta-small">План</div><h1 class="page-title">Календарь</h1><p class="page-description">Планируй события и важные даты</p></div><button class="primary-icon-button" onclick="openEventAdd()" aria-label="Добавить событие">${icon.plus}</button></div><div class="quick-days"><button onclick="goToday()">Сегодня</button><button onclick="setRelativeDay(1)">Завтра</button><button onclick="setRelativeDay(7)">Через неделю</button></div>${order.map(k=>sections[k]).join('')}</div>`;
}
export function goToday(){const d=new Date();selectedDate=d;visibleMonth=new Date(d.getFullYear(),d.getMonth(),1);renderCalendar();}
export function selectCalendarDate(key){selectedDate=new Date(key+'T12:00:00');visibleMonth=new Date(selectedDate.getFullYear(),selectedDate.getMonth(),1);renderCalendar();}
export function changeCalendarMonth(dir){visibleMonth=new Date(visibleMonth.getFullYear(),visibleMonth.getMonth()+dir,1);renderCalendar();}
export function setRelativeDay(days){const d=new Date();d.setDate(d.getDate()+days);selectCalendarDate(dayKey(d));}
export function openEventAdd(editId=''){
  const existing=editId?state.entries.find(x=>x.id===editId):null; const initial=existing?dayKey(new Date(existing.event_date)):dayKey(selectedDate);
  const modal=document.createElement('div'); modal.className='modal-bg'; modal.onclick=e=>{if(e.target===modal)modal.remove()};
  modal.innerHTML=`<div class="modal apple-sheet"><div class="modal-handle"></div><div class="sheet-title-row"><div><div class="meta-small">Календарь</div><h2>${existing?'Изменить событие':'Новое событие'}</h2></div><button class="sheet-close" onclick="this.closest('.modal-bg').remove()">×</button></div><label>Название<input id="newEventTitle" value="${existing?escapeHtml(existing.title):''}" placeholder="Например, встреча или дедлайн"></label><label>Дата<input id="newEventDate" type="date" value="${initial}"></label><button class="primary sheet-primary" onclick="${existing?`saveEventEdit('${existing.id}')`:'saveNewEvent()'}">${existing?'Сохранить изменения':'Добавить событие'}</button><button class="ghost sheet-cancel" onclick="this.closest('.modal-bg').remove()">Отмена</button></div>`;
  document.body.appendChild(modal); modal.querySelector('#newEventTitle')?.focus();
}
export function editEvent(id){openEventAdd(id);}
export async function saveEventEdit(id){
  const e=state.entries.find(x=>x.id===id); const title=document.getElementById('newEventTitle')?.value.trim(); const dateVal=document.getElementById('newEventDate')?.value; if(!e||!title||!dateVal)return;
  e.title=title; e.event_date=new Date(dateVal+'T12:00:00').toISOString(); e.updated_at=new Date().toISOString(); selectedDate=new Date(dateVal+'T12:00:00'); document.querySelector('.modal-bg')?.remove(); cacheEntries([e]); enqueue('entries','update',{id,title,event_date:e.event_date,updated_at:e.updated_at}); renderCalendar();
}
export async function saveNewEvent(){const title=document.getElementById('newEventTitle')?.value.trim();const dateVal=document.getElementById('newEventDate')?.value;if(!title||!dateVal)return;const now=new Date().toISOString();const row={id:crypto.randomUUID(),type:'event',title,event_date:new Date(dateVal+'T12:00:00').toISOString(),user_id:state.session.user.id,created_at:now,updated_at:now,done:false,category:'Календарь'};state.entries.push(row);selectedDate=new Date(dateVal+'T12:00:00');document.querySelector('.modal-bg')?.remove();cacheEntries([row]);enqueue('entries','insert',row);renderCalendar();}
export function deleteCalendarEvent(id){deleteEntry(id);renderCalendar();}
export function addEventToPhoneCalendar(id){const e=state.entries.find(x=>x.id===id);if(!e?.event_date)return;const d=new Date(e.event_date);const y=d.getUTCFullYear();const m=String(d.getUTCMonth()+1).padStart(2,'0');const day=String(d.getUTCDate()).padStart(2,'0');const ics=['BEGIN:VCALENDAR','VERSION:2.0','BEGIN:VEVENT',`UID:${e.id}@put-app`,`DTSTAMP:${d.toISOString().replace(/[-:]/g,'').split('.')[0]}Z`,`DTSTART;VALUE=DATE:${y}${m}${day}`,`SUMMARY:${e.title.replace(/\n/g,' ')}`,'END:VEVENT','END:VCALENDAR'].join('\r\n');const blob=new Blob([ics],{type:'text/calendar;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${e.title.slice(0,30)||'event'}.ics`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);}
